services:
  - type: web
    name: backend-tmdt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
