services:
  - type: web
    name: backend-tmdt
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --bind=0.0.0.0:10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
